### ISSUE TITLE
Shelly EM

### ISSUE THREAD

**Issue by pjmm1** [dresdner353/energyutils#1]
Hi I am trying to get the data from the Shelly EM using your script.
It created the Shelly directory but doesn't put any files in it
Can you help
Out put from CMD Shell

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET PYTHON=python3.exe

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET SHELLY_DATA=shelly_data

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET SHELLY_SCRIPT=..\shelly_em_data_util.py

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET GEN_REPORT_SCRIPT=..\gen_report.py

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET REPORTS=day week month year hour tariff 24h weekday

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>REM Shelly API config

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET SET SHELLY_HOST=shelly-36-eu.shelly.cloud

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET SET SHELLY_AUTH_KEY=YTUyZGZ1aWQXXXXXXXXXXX

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>SET SET SHELLY_DEVICE_ID=485XXXXXXXX
C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>REM prepare directory for parsed SHELLY JSON data

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>IF not exist shelly_data (mkdir shelly_data )

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>REM Retrieve data from Shelly Cloud

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>python3.exe ..\shelly_em_data_util.py     --host      --id      --auth_key      --odir "shelly_data"     --days 30
usage: shelly_em_data_util.py [-h] --host HOST [--odir ODIR] [--days DAYS] [--solar_discard SOLAR_DISCARD] --id ID
                              --auth_key AUTH_KEY [--verbose]
shelly_em_data_util.py: error: argument --host: expected one argument

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>REM Example EV report

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>python3.exe ..\gen_report.py     --idir shelly_data     --file shelly_report_ev.xlsx     --reports day week month year hour tariff 24h weekday     --tariff_rate Day:0.4320 Night:0.2086 Boost:0.1225     --tariff_interval 08-23:Day 23-08:Night 02-04:Boost     --annual_standing_charge 303     --fit_rate 0.21
Sun Feb 25 16:16:39 2024 Generating report shelly_report_ev.xlsx
Sun Feb 25 16:16:39 2024 Loaded 0 files, 0 records

C:\AAAShelly\ESB Report Program\energyutils-main\energyutils-main\windows_workflow>pause
Press any key to continue . . .

**Comment by dresdner353** [comment]
In the script, it seems you have "SET SET VARIABLE=VALUE" in the section for the API config. "SET" is there twice. Try removing the leading SET so that they all read with only one "SET" directive and then the value for your device/account... 

```
REM Shelly API config
SET SHELLY_HOST=example.com
SET SHELLY_AUTH_KEY=ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
SET SHELLY_DEVICE_ID=000000000000
```

**Comment by pjmm1** [comment]
Excellent I now have both programs working.
I read that ESB had opened a portal where you could log on and download the hdf file
It would be good to incorporate this feature into your program
Great Work
Many thanks
