### ISSUE TITLE
Report Start and end

### ISSUE THREAD

**Issue by pjmm1** [dresdner353/energyutils#3]
REM Example EV report
%PYTHON% %GEN_REPORT_SCRIPT% ^
    --idir %SHELLY_DATA% ^
    --start START         Calculation Start Date (20230302)
    --end END             Calculation End Date (20230303)
	--file shelly_report_ev.xlsx ^
    --reports %REPORTS% ^
    --hide_columns year month week ts ^
    --tariff_rate Day:0.2692 Night:0.1576  ^
    --tariff_interval 08-23:Day 23-08:Night  ^
    --annual_standing_charge 226 ^
    --fit_rate 0.12 

C:\AAAShelly\ESB Report Program\energyutils-main\windows_workflow>--end END             Calculation End Date (20230303)
'--end' is not recognized as an internal or external command,
operable program or batch file.
What am I not doing correctly
PJM

**Comment by dresdner353** [comment]
You're using the wrong syntax on the --start and --end options

looks like you've copied in the text from the help detail. Should read as follows:

--start YYYYMMDD ^
--end YYYYMMDD  ^

e.g generate report on data between March 2nd 2023 and Sep 5th 2023:

--start 20230302 ^
--end 20230905  ^

Also note the terminating ^ at the end of each line

**Comment by pjmm1** [comment]
Hi

that all looks good

Would you consider making a front end where you would have all the 
variability

Start date, Finish date, Tariffs, Directory, File Name etc

Have this editable and have it create all the variables in the .bat file.

Regards

PJM

**Comment by dresdner353** [comment]
These are scripts and are defined for portability. I've given workflows for both windows (batch file) and shell script variations for MacOS and Linux. That is about as much help as it can offer really. Users need to go from there to customise the flow etc. 

Front-ends are a whole other undertaking and grow too many legs.

I will however review all the options and enhance the documentation to better explain how to use the addiitonal options.
